### PR TITLE
Align the generic type names to the ZIO ones, replacing `Environment` by `R`, `Error` by `E` and `Value` by `A`

### PR DESCRIPTION
**Pull request by guizmaii**

### CODE REVIEW

**Comment by adamgfraser** [comment]
I'm somewhat 👎 on this. More descriptive type parameter names are used in ZIO itself for things like ZIO Stream and ZIO Schedule and can be helpful when some of the type parameters are different, for example `Key` and `Value`. So this seems like change that if anything reduces clarity.

**Comment by guizmaii** [comment]
@adamgfraser the thing is these long names make the code hard to read. Also, any ZIO user is super familiar with ZIO[R, E, A] and so is more familiar with my proposal than the previous names. It makes the code more readable.
`[R, E, A]` is part of the "marketing" around ZIO since the beginning. To me, it makes sense to align across projects

Note that I've left `Key` as is because it's a new thing compared to `ZIO[R, E, A]`

**Comment by adamgfraser** [comment]
I'm just not sure what we are aligning on. In ZIO itself we have, among other things:

```scala
trait Schedule[-Env, -In, +Out]
sealed trait ZChannel[-Env, -InErr, -InElem, -InDone, +OutErr, +OutElem, +OutDone]
final class ZPipeline[-Env, +Err, -In, +Out]
final class ZSink[-R, +E, -In, +L, +Z]
```

I think our experience has generally been that while longer type parameter names make code slightly longer they also enhance clarity by saying exactly what each type parameter is and that has generally been a good trade-off. Especially here there is generally no need for you to use the longer type parameter names in your own code as a user of the library so the cost of longer names is particularly low.

Finally, I think mixing the "generic" and domain specific type parameter names can be quite akward. So if all we had were environment, error, and value types `R, E, A` makes quite a bit of sense but as soon as you introduce something else like `Key` I would want to move over to more descriptive type parameter names throughout.

But there is definitely some subjectivity here.

**Comment by guizmaii** [comment]
> Finally, I think mixing the "generic" and domain specific type parameter names can be quite awkward.

Agreed. My initial idea was to rename `Key` to `K` but I was trying to be gentle 😄
I can change to `K` if you want 😛

More seriously, that's definitely subjective :/

**Comment by adamgfraser** [comment]
This doesn't seem to be a clear improvement so let's just keep it as is.

**Pull request closed without merging**
