### PR TITLE
Delete CacheWorth

### PR DESCRIPTION
**Pull request by adamgfraser**
Deletes the `CacheWorth` data type. `CacheWorth` basically models three possible states, greater than, less than, and equalTo, isomorphic to the `Ordering` data type in ZIO Prelude that is the result of the `compare` operator on `Ord`. I don't think this really pulls its weight as its own data type. If we just have the `compare` operators on `CachingPolicy` and `Priority` return an `Int` analogous to `scala.math.Ordering` and `java.lang.Comparable` we can simplify interoperation with these abstractions and take advantage of existing intuition about them.

This also makes the semantics of `CachingPolicy` and `Priority` more intuitive. An entry that is "greater" in priority in the caching policy is more important and should be retained over an entry with "lower" priority.

### CODE REVIEW

**Comment by adamgfraser** [comment]
It also dramatically improves performance on the churn benchmark.

Before:

```
[info] Benchmark                     (size)   Mode  Cnt   Score   Error  Units
[info] ChurnBenchmark.zioCacheChurn   10000  thrpt   25  58.555 ± 1.797  ops/s
[info] FillBenchmark.zioCacheFill     10000  thrpt   25  60.027 ± 1.071  ops/s
```

After:

```
[info] Benchmark                     (size)   Mode  Cnt    Score   Error  Units
[info] ChurnBenchmark.zioCacheChurn   10000  thrpt   25  165.935 ± 2.582  ops/s
[info] FillBenchmark.zioCacheFill     10000  thrpt   25   63.105 ± 1.401  ops/s
```

**Comment by jdegoes** [comment]
Wow. Amazing.

**Comment by jdegoes** [comment]
We should make sure that decorations and laziness at the order of the `Ordering` compare don't affect results (since that's what this was likely due to).

**Comment by adamgfraser** [comment]
The other issue is that the semantics of the benchmark changed. The churn benchmark uses `CachingPolicy.byLastAccess` which previously meant "keep the oldest value" and now means "keep the newest value". I think the new semantics are much more intuitive but it means the benchmark got easier because after the first run the cache gets filled with the new entries and everything is a cache hit after that.

Flipping the caching policy so it is the oldest values that are kept and every attempt to get the new values results in a cache miss still gives much better performance.

```
[info] Benchmark                     (size)   Mode  Cnt    Score   Error  Units
[info] ChurnBenchmark.zioCacheChurn   10000  thrpt   25  124.907 ± 3.175  ops/s
[info] FillBenchmark.zioCacheFill     10000  thrpt   25   61.965 ± 2.178  ops/s
```

**Comment by jdegoes** [comment]
Excellent catch, and we're still ahead so I'm happy!

**Pull request merged**
