### PR TITLE
Update Scala, ScalaJS, Scala-Native, ZIO, sbt, sbt plugins and CI definition

### PR DESCRIPTION
**Pull request by guizmaii**

### CODE REVIEW

**Review by adamgfraser — CHANGES_REQUESTED** [review]
I don't think we need to drop the Scala 2.11 support. `scala-java-time` is only used as a test dependency for ScalaJS so we could just not run tests on Scala 2.11 / ScalaJS or use the previous version.

**Comment by guizmaii** [comment]
@adamgfraser Fixed. Thanks for your review and sorry about that, I should have seen it.

**Review by adamgfraser — DISMISSED** [review]
Can you merge upstream changes?

**Comment by guizmaii** [comment]
> Can you merge upstream changes?

Done

**Review by adamgfraser — APPROVED** [review]

**Pull request merged**
