### PR TITLE
add a way to clean expired resource in ScopedCache

### PR DESCRIPTION
**Pull request by strokyl**
My team with ScopedCache to cache Kafka admin client. admin client has their own threads in the background, which mean keeping them alive have a cost. Therefore we want to close them when there are expired even if the cache isn't full yet.

### CODE REVIEW

**Review by sderosiaux — APPROVED** [review]

**Comment by adamgfraser** [comment]
This feels like an implementation leak. Why are these resources not being released on a timely basis?

**Comment by strokyl** [comment]
> This feels like an implementation leak. Why are these resources not being released on a timely basis?

Before my PR, the TTL was only checked on a `.get` and a resource with an expired TTL was discarded and replaced by a new resource.
If I understood, you would like that the ScopedCache automatically throw away expired resources as soon as they expire?

**Comment by adamgfraser** [comment]
I think it would be nice if the cache handled releasing these resources so the user didn't have to directly. We could do this in a couple ways:

1. Release expired resources as soon as they expire.
2. Check for expired items regularly on other cache operations.
3. Create a background process to release expired cache resources on some interval

**Comment by strokyl** [comment]
> 1. Release expired resources as soon as they expire.

This will mean setting a fiber with a ZIO.sleep for each resources created? Isn't it too costly? Otherwise we can imagine having a watcher waking up for each TTL/N. (But the TTL is a function and not a constant of the resource builder result, therefore the last option isn't really easy)

> 2. Check for expired items regularly on other cache operations.

Do you want to do AND 1. or 1. OR 2.

**Comment by adamgfraser** [comment]
I think a single background fiber that checks for expired entries on some interval, say every second, would be a simple solution that would address the issue with minimal performance impact.

**Comment by strokyl** [comment]
Sorry by mistake I duplicated the PR: 
https://github.com/zio/zio-cache/pull/133

**Pull request closed without merging**
