### PR TITLE
Fix publishing: remove dependency on `"io.github.cquiroz" %%% "scala-java-time"` (Not published for Scala2.11)

### PR DESCRIPTION
**Pull request by guizmaii**

### CODE REVIEW

**Review by adamgfraser — CHANGES_REQUESTED** [review]
Can we add back testing on Scala 2.11 as part of CI?

**Comment by guizmaii** [comment]
> Can we add back testing on Scala 2.11 as part of CI?

Sure :)

**Comment by guizmaii** [comment]
@adamgfraser Done :)

**Comment by adamgfraser** [comment]
@guizmaii It looks like the build is failing.

**Comment by guizmaii** [comment]
@adamgfraser Can we maybe merge this PR and release a new version, please?

**Comment by adamgfraser** [comment]
@guizmaii It needs to pass CI first.

**Review by adamgfraser — APPROVED** [review]

**Pull request merged**
